src/Entity/Grupo.php
<?php

namespace App\Entity;

use App\Repository\GrupoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GrupoRepository::class)]
class Grupo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $nombre;

    #[ORM\OneToMany(mappedBy: 'grupo', targetEntity: User::class)]
    private $miembros;

    #[ORM\OneToOne( inversedBy: 'creador', targetEntity: User::class, cascade: ['persist', 'remove'])]
    private $autor;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $juego;

    public function __construct()
    {
        $this->miembros = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getMiembros(): Collection
    {
        return $this->miembros;
    }

    public function addMiembro(User $miembro): self
    {
        if (!$this->miembros->contains($miembro)) {
            $this->miembros[] = $miembro;
            $miembro->setGrupo($this);
        }

        return $this;
    }

    public function removeMiembro(User $miembro): self
    {
        if ($this->miembros->removeElement($miembro)) {
            // set the owning side to null (unless already changed)
            if ($miembro->getGrupo() === $this) {
                $miembro->setGrupo(null);
            }
        }

        return $this;
    }

    public function getAutor(): ?User
    {
        return $this->autor;
    }

    public function setAutor(?User $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getJuego(): ?string
    {
        return $this->juego;
    }

    public function setJuego(?string $juego): self
    {
        $this->juego = $juego;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 50)]
    private $discord;

    #[ORM\Column(type: 'string', length: 255)]
    private $username;

    #[ORM\Column(type: 'string', length: 50, nullable: true)]
    private $Rango;

    #[ORM\ManyToOne(targetEntity: Grupo::class, inversedBy: 'miembros')]
    private $grupo;

    #[ORM\OneToOne(mappedBy: 'autor', targetEntity: Grupo::class, cascade: ['persist', 'remove'])]
    private $creador;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $Baneado;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $rangoValorant;

    #[ORM\OneToMany(mappedBy: 'Autor', targetEntity: Reporte::class)]
    private $reportes;

    #[ORM\OneToMany(mappedBy: 'Reportado', targetEntity: Reporte::class)]
    private $reportedIn;

    public function __construct()
    {
        $this->reportes = new ArrayCollection();
        $this->reportedIn = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDiscord(): ?string
    {
        return $this->discord;
    }

    public function setDiscord(string $discord): self
    {
        $this->discord = $discord;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRango(): ?string
    {
        return $this->Rango;
    }

    public function setRango(?string $Rango): self
    {
        $this->Rango = $Rango;

        return $this;
    }

    public function getGrupo(): ?Grupo
    {
        return $this->grupo;
    }

    public function setGrupo(?Grupo $grupo): self
    {
        $this->grupo = $grupo;

        return $this;
    }

    public function getCreador(): ?Grupo
    {
        return $this->creador;
    }

    public function setCreador(?Grupo $creador): self
    {
        // unset the owning side of the relation if necessary
        if ($creador === null && $this->creador !== null) {
            $this->creador->setAutor(null);
        }

        // set the owning side of the relation if necessary
        if ($creador !== null && $creador->getAutor() !== $this) {
            $creador->setAutor($this);
        }

        $this->creador = $creador;

        return $this;
    }

    public function isBaneado(): ?bool
    {
        return $this->Baneado;
    }

    public function setBaneado(?bool $Baneado): self
    {
        $this->Baneado = $Baneado;

        return $this;
    }

    public function getRangoValorant(): ?string
    {
        return $this->rangoValorant;
    }

    public function setRangoValorant(?string $rangoValorant): self
    {
        $this->rangoValorant = $rangoValorant;

        return $this;
    }

    /**
     * @return Collection<int, Reporte>
     */
    public function getReportes(): Collection
    {
        return $this->reportes;
    }

    public function addReporte(Reporte $reporte): self
    {
        if (!$this->reportes->contains($reporte)) {
            $this->reportes[] = $reporte;
            $reporte->setAutor($this);
        }

        return $this;
    }

    public function removeReporte(Reporte $reporte): self
    {
        if ($this->reportes->removeElement($reporte)) {
            // set the owning side to null (unless already changed)
            if ($reporte->getAutor() === $this) {
                $reporte->setAutor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reporte>
     */
    public function getReportedIn(): Collection
    {
        return $this->reportedIn;
    }

    public function addReportedIn(Reporte $reportedIn): self
    {
        if (!$this->reportedIn->contains($reportedIn)) {
            $this->reportedIn[] = $reportedIn;
            $reportedIn->setReportado($this);
        }

        return $this;
    }

    public function removeReportedIn(Reporte $reportedIn): self
    {
        if ($this->reportedIn->removeElement($reportedIn)) {
            // set the owning side to null (unless already changed)
            if ($reportedIn->getReportado() === $this) {
                $reportedIn->setReportado(null);
            }
        }

        return $this;
    }
}

src/Form/GrupoType.php
<?php

namespace App\Form;

use App\Entity\Grupo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GrupoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Grupo::class,
        ]);
    }
}

src/Controller/GrupoController.php
<?php

namespace App\Controller;

use App\Entity\Grupo;
use App\Form\GrupoType;
use App\Repository\GrupoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\User;

#[Route('/grupo')]
class GrupoController extends AbstractController
{
    #[Route('/', name: 'app_grupo_index', methods: ['GET'])]
    public function index(GrupoRepository $grupoRepository): Response
    {
        return $this->render('grupo/indexlol.html.twig', [
            'grupos' => $grupoRepository->findAll(),
        ]);
    }
    #[Route('/grupo2', name: 'app_grupo_index2', methods: ['GET'])]
    public function grupo2(GrupoRepository $grupoRepository): Response
    {
        return $this->render('grupo/indexvalorant.html.twig', [
            'grupos' => $grupoRepository->findAll(),
        ]);
    }
    #[Route('/', name: 'app_grupo_show', methods: ['GET'])]
    public function index2(GrupoRepository $grupoRepository): Response
    {
        return $this->render('grupo/show.html.twig', [
            'grupos' => $grupoRepository->findAll(),
        ]);
    }
    #[Route('/{grupo}/unirse', name: 'unirse', methods: ['GET'])]
    public function unirse(Grupo $grupo,EntityManagerInterface $entityManager): Response
    {
            
            $grupo->addMiembro($this->getUser());

            $entityManager->persist($grupo);
            $entityManager->flush();

            return $this->render('grupo/show.html.twig', [
                'grupo' => $grupo,
            ]);
        
    }

    #[Route('/new', name: 'app_grupo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, GrupoRepository $grupoRepository): Response
    {
        $grupo = new Grupo();
        $form = $this->createForm(GrupoType::class, $grupo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $grupoRepository->add($grupo, true);
            $grupo->setAutor($this->getUser());
            $grupo->addMiembro($this->getUser());

            $entityManager->persist($grupo);
            $entityManager->flush();

            return $this->redirectToRoute('grupos', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('grupo/new.html.twig', [
            'grupo' => $grupo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_grupo_show', methods: ['GET'])]
    public function show(Grupo $grupo): Response
    {
        return $this->render('grupo/show.html.twig', [
            'grupo' => $grupo,
        ]);
    }
    #[Route('show/{id}', name: 'app_grupo_show2', methods: ['GET'])]
    public function show2(Grupo $grupo): Response
    {
        return $this->render('grupo/show2.html.twig', [
            'grupo' => $grupo,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_grupo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Grupo $grupo, GrupoRepository $grupoRepository): Response
    {
        $form = $this->createForm(GrupoType::class, $grupo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $grupoRepository->add($grupo, true);

            return $this->redirectToRoute('app_grupo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('grupo/edit.html.twig', [
            'grupo' => $grupo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_grupo_delete', methods: ['GET','POST'])]
    public function delete(Grupo $grupo,EntityManagerInterface $entityManager,Request $request, GrupoRepository $grupoRepository): Response
    {
        // User $user,

        $grupo->removeMiembro($this->getUser());
        
            if (count($grupo->getMiembros()) <=0 ) {
                $grupo->setAutor(null);
                $entityManager->remove($grupo);
                $entityManager->flush();
            }
            else{
                $entityManager->persist($grupo);
                $entityManager->flush();
            }
        

        
        // if ($this->isCsrfTokenValid('delete'.$grupo->getId(), $request->request->get('_token'))) {
        //     $grupoRepository->remove($grupo, true);
        // }

        return $this->redirectToRoute('grupos', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/{id}', name: 'app_grupo_delete2', methods: ['POST'])]
    public function delete2(Grupo $grupo,EntityManagerInterface $entityManager,Request $request,User $user, GrupoRepository $grupoRepository): Response
    {
            
        $grupoRepository->remove($grupo);

        // $entityManager->persist($grupo);
        // $entityManager->flush();

        return $this->redirectToRoute('app_grupo_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/grupo/_delete_form.html.twig
<form method="post" action="{{ path('app_grupo_delete', {'id': grupo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ grupo.id) }}">
    <button>Salir</button>
</form>

templates/grupo/_delete_form2.html.twig
<form method="post" action="{{ path('app_grupo_delete2', {'id': grupo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ grupo.id) }}">
    <button>Borrar Grupo</button>
</form>

templates/grupo/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Crear') }}</button>
{{ form_end(form) }}

templates/grupo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Grupo{% endblock %}

{% block body %}
    <h1>Edit Grupo</h1>

    {{ include('grupo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_grupo_index') }}">back to list</a>

    {{ include('grupo/_delete_form.html.twig') }}
{% endblock %}

templates/grupo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grupo index{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}

<section id ="listaLibros">
    <h1>Lista de Grupos</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Miembros</th>
                <th>Acceder</th>
            </tr>
        </thead>
        <tbody>
        {% for grupo in grupos %}
            <tr>
                <td>{{ grupo.nombre }}</td>
                <td>{{grupo.miembros|length}}/5</td>
                <td>
                    <a href="{{ path('app_grupo_show', {'id': grupo.id}) }}">Mostrar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button>
    <a href="{{ path('app_grupo_new') }}">Crear Grupo</a>
    </button>
    <br>
    <button>
    <a href="{{ path('admin') }}">Volver ↩</a>
    </button>
    </section>
    {{ include('./admin/footer.html.twig')}}
{% endblock %}

templates/grupo/indexlol.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grupo index{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}

<section id ="listaLibros">
    <h1>Grupos Lol</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Miembros</th>
                <th>Acceder</th>
            </tr>
        </thead>
        <tbody>
        {% for grupo in grupos %}
            {% if grupo.juego == "Lol" %}
            <tr>
                <td>{{ grupo.nombre }}</td>
                <td>{{grupo.miembros|length}}/5</td>
                <td>
                    <a href="{{ path('app_grupo_show', {'id': grupo.id}) }}">Mostrar</a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button>
    <a href="{{ path('app_grupo_new') }}">Crear Grupo</a>
    </button>
    <br>
    <button>
    <a href="{{ path('grupos') }}">Volver ↩</a>
    </button>
    </section>
    {{ include('./admin/footer.html.twig')}}
{% endblock %}

templates/grupo/indexvalorant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grupo index{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}

<section id ="listaLibros">
    <h1>Grupos Valorant</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Miembros</th>
                <th>Acceder</th>
            </tr>
        </thead>
        <tbody>
        {% for grupo in grupos %}
            {% if grupo.juego == "Valorant" %}
            <tr>
                <td>{{ grupo.nombre }}</td>
                <td>{{grupo.miembros|length}}/5</td>
                <td>
                    <a href="{{ path('app_grupo_show2', {'id': grupo.id}) }}">Mostrar</a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button>
    <a href="{{ path('app_grupo_new') }}">Crear Grupo</a>
    </button>
    <br>
    <button>
    <a href="{{ path('grupos') }}">Volver ↩</a>
    </button>
    </section>
    {{ include('./admin/footer.html.twig')}}
{% endblock %}

templates/grupo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Grupo{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}
<section id = "edit">
    <h1>Crear Nuevo Grupo</h1>
    <div id="form">
    {{ include('grupo/_form.html.twig') }}
    </div>
    <button>
    <a href="{{ path('grupos') }}">Volver al listado</a>
    </button>
    </section>
        {{ include('./admin/footer.html.twig')}}
{% endblock %}

templates/grupo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grupo{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}
<section id = "listaLibros">
    <table class="table">
        <tbody>
            <tr>
                <td><h3>{{grupo.nombre}}</h3></td>
                <td>Username</td>
                <td>Discord</td>
                <td>Rango</td>
                <td>Acciones</td>
            </tr>
            {% for miembro in grupo.miembros %}
            {% if miembro.username == app.user.username %}
            <tr>
                <th>Jugador</th>
                <td>
                    {{miembro.username}}
                </td>
                <td>
                    {{miembro.discord}}
                </td>
                <td>
                    {{miembro.rango}}
                </td>
                <td>
                    {# <button>
                        <a href="/reporte/{{miembro.id}}/new">Reportar jugador</a>
                    </button> #}
                </td>
            </tr>
            {% else %}
            <tr>
                <th>Jugador</th>
                <td>
                    {{miembro.username}}
                </td>
                <td>
                    {{miembro.discord}}
                </td>
                <td>
                    {{miembro.rango}}
                </td>
                <td>
                        <a href="/reporte/{{miembro.id}}/new">Reportar</a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <div class= "enlacesAdmin">
    <button>
    <a href="{{ path('grupos') }}">Volver al Buscador</a>
    </button>
    
    {% if grupo.miembros|length < 5 %}
    <button>
    <a href = "/grupo/{{ grupo.id }}/unirse">Unirse</a>
    </button>
    {% endif %}
        {{ include('grupo/_delete_form.html.twig') }}
    </div>
</section>
    

    {{ include('./admin/footer.html.twig')}}
{% endblock %}

templates/grupo/show2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grupo{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}

<section id = "listaLibros">
    <table class="table">
        <tbody>
            <tr>
                <td><h3>{{grupo.nombre}}</h3></td>
                <td>Username</td>
                <td>Discord</td>
                <td>Rango</td>
                <td>Acciones</td>
            </tr>
            {% for miembro in grupo.miembros %}
            {% if miembro.username == app.user.username %}
            <tr>
                <th>Jugador</th>
                <td>
                    {{miembro.username}}
                </td>
                <td>
                    {{miembro.discord}}
                </td>
                <td>
                    {{miembro.rangoValorant}}
                </td>
                <td>
                    {# <button>
                        <a href="/reporte/{{miembro.id}}/new">Reportar jugador</a>
                    </button> #}
                </td>
            </tr>
            {% else %}
            <tr>
                <th>Jugador</th>
                <td>
                    {{miembro.username}}
                </td>
                <td>
                    {{miembro.discord}}
                </td>
                <td>
                    {{miembro.rangoValorant}}
                </td>
                <td>
                    
                        <a href="/reporte/{{miembro.id}}/new">Reportar</a>
                    
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    <div class= "enlacesAdmin">
    <button>
    <a href="{{ path('grupos') }}">Volver al Buscador</a>
    </button>
    
    {% if grupo.miembros|length < 5 %}
    <button>
    <a href = "/grupo/{{ grupo.id }}/unirse">Unirse</a>
    </button>
    {% endif %}
        {{ include('grupo/_delete_form.html.twig') }}
    </div>
</section>
    

    {{ include('./admin/footer.html.twig')}}
{% endblock %}