src/Entity/Reporte.php
<?php

namespace App\Entity;

use App\Repository\ReporteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReporteRepository::class)]
class Reporte
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'reportes')]
    private $Autor;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Descripcion;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'reportedIn')]
    private $Reportado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAutor(): ?User
    {
        return $this->Autor;
    }

    public function setAutor(?User $Autor): self
    {
        $this->Autor = $Autor;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(?string $Descripcion): self
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getReportado(): ?User
    {
        return $this->Reportado;
    }

    public function setReportado(?User $Reportado): self
    {
        $this->Reportado = $Reportado;

        return $this;
    }
}

src/Form/ReporteType.php
<?php

namespace App\Form;

use App\Entity\Reporte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReporteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Descripcion')
            // ->add('Autor')
            // ->add('Reportado')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reporte::class,
        ]);
    }
}

src/Controller/ReporteController.php
<?php

namespace App\Controller;

use App\Entity\Reporte;
use App\Entity\User;
use App\Form\ReporteType;
use App\Repository\ReporteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/reporte')]
class ReporteController extends AbstractController
{
    #[Route('/', name: 'app_reporte_index', methods: ['GET'])]
    public function index(ReporteRepository $reporteRepository): Response
    {
        return $this->render('reporte/index.html.twig', [
            'reportes' => $reporteRepository->findAll(),
        ]);
    }

    #[Route('/{id}/new', name: 'app_reporte_new', methods: ['GET', 'POST'])]
    public function new( User $user, EntityManagerInterface $entityManager, Request $request, ReporteRepository $reporteRepository): Response
    {

        $reporte = new Reporte();
        $form = $this->createForm(ReporteType::class, $reporte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reporteRepository->add($reporte);
            $reporte->setAutor($this->getUser());
            $reporte->setReportado($user);

            $entityManager->persist($reporte);
            $entityManager->flush();
            return $this->redirectToRoute('app_grupo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reporte/new.html.twig', [
            'reporte' => $reporte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reporte_show', methods: ['GET'])]
    public function show(Reporte $reporte): Response
    {
        return $this->render('reporte/show.html.twig', [
            'reporte' => $reporte,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reporte_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reporte $reporte, ReporteRepository $reporteRepository): Response
    {
        $form = $this->createForm(ReporteType::class, $reporte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reporteRepository->add($reporte, true);

            return $this->redirectToRoute('app_reporte_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reporte/edit.html.twig', [
            'reporte' => $reporte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reporte_delete', methods: ['POST'])]
    public function delete(Request $request, Reporte $reporte, ReporteRepository $reporteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reporte->getId(), $request->request->get('_token'))) {
            $reporteRepository->remove($reporte, true);
        }

        return $this->redirectToRoute('app_reporte_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reporte/_delete_form.html.twig
<form method="post" action="{{ path('app_reporte_delete', {'id': reporte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reporte.id) }}">
    <button class="btn">Borrar</button>
</form>

templates/reporte/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enviar') }}</button>
{{ form_end(form) }}

templates/reporte/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reporte{% endblock %}

{% block body %}
    <h1>Edit Reporte</h1>

    {{ include('reporte/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reporte_index') }}">back to list</a>

    {{ include('reporte/_delete_form.html.twig') }}
{% endblock %}

templates/reporte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reporte index{% endblock %}

{% block body %}
{{ include('./admin/adminheader.html.twig')}}


    <section id="userList">
        <h1>Lista de reportes</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Autor</th>
                <th>Reportado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for reporte in reportes %}
            <tr>
                <td>{{ reporte.id }}</td>
                <td>{{ reporte.autor.username }}</td>
                <td>{{ reporte.reportado.username }}</td>
                <td>
                    <a href="{{ path('app_reporte_show', {'id': reporte.id}) }}">Mostrar</a>
                    </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button>
	<a href="{{ path('gestion') }}">Volver ↩</a>
	</button>
    </section>
    {{ include('./admin/footer.html.twig')}}
    {# <a href="{{ path('app_reporte_new', {'id': reporte.id}) }}">Create new</a> #}
{% endblock %}

templates/reporte/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reporte{% endblock %}

{% block body %}
{{ include('./admin/header.html.twig')}}
<section id = "edit">
    <h1>Dínos la razón de tu reporte</h1>
    <div id= "form">
    {{ include('reporte/_form.html.twig') }}
    </div>
    </section>
{{ include('./admin/footer.html.twig')}}
{% endblock %}

templates/reporte/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reporte{% endblock %}

{% block body %}
{{ include('./admin/adminheader.html.twig')}}


    <section id="userList">
    <h1>Reporte</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Descripcion</th>
                <td>{{ reporte.Descripcion }}</td>
            </tr>
            <tr>
                <th>Autor</th>
                <td>{{ reporte.autor.username }}</td>
            </tr>
            <tr>
                <th>Reportado</th>
                <td>{{ reporte.reportado.username }}</td>
            </tr>
        </tbody>
    </table>
    <button>
    <a href="{{ path('app_reporte_index') }}">Volver al listado</a>
    </button>

    {{ include('reporte/_delete_form.html.twig') }}
    </section>
    {{ include('./admin/footer.html.twig')}}
{% endblock %}